"""initial schema

Revision ID: 4045e1f7253b
Revises: 
Create Date: 2026-08-26 10:11:42.006228
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import ariadne.storage.postgres.models

revision: str = '4045e1f7253b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_pricing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('input_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('output_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_read_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_write_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('reasoning_per_million', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pricing_lookup', 'model_pricing', ['provider', 'model', 'effective_from'], unique=False)
    op.create_table('organizations',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('org_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_project_slug')
    )
    op.create_table('datasets',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('project_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_dataset_version')
    )
    op.create_index('ix_datasets_project', 'datasets', ['project_id', 'name'], unique=False)
    op.create_table('judge_calibrations',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('project_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('judge_model', sa.String(length=200), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('kappa', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('weighting', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_calibration_lookup', 'judge_calibrations', ['project_id', 'judge_model', 'dimension'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('project_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('variables', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', 'version', name='uq_prompt_version')
    )
    op.create_index('ix_prompts_project_name', 'prompt_versions', ['project_id', 'name'], unique=False)
    op.create_table('dataset_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('item_id', sa.String(length=200), nullable=False),
    sa.Column('input', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('item_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'item_id', name='uq_dataset_item')
    )
    op.create_table('experiments',
    sa.Column('id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('project_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=False),
    sa.Column('dataset_id', ariadne.storage.postgres.models.UuidType(length=36), nullable=True),
    sa.Column('dataset_ref', sa.String(length=300), nullable=False),
    sa.Column('config_label', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('judge_models', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('total_cost_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('pending','running','completed','failed','cancelled')", name='ck_experiment_status'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_experiments_project_created', 'experiments', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_experiments_project_created', table_name='experiments')
    op.drop_table('experiments')
    op.drop_table('dataset_items')
    op.drop_index('ix_prompts_project_name', table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index('ix_calibration_lookup', table_name='judge_calibrations')
    op.drop_table('judge_calibrations')
    op.drop_index('ix_datasets_project', table_name='datasets')
    op.drop_table('datasets')
    op.drop_table('projects')
    op.drop_table('organizations')
    op.drop_index('ix_pricing_lookup', table_name='model_pricing')
    op.drop_table('model_pricing')
    # ### end Alembic commands ###
